### ISSUE TITLE
Remove source rpm from repository

### ISSUE THREAD

**Issue by mreiden** [aws/amazon-ec2-net-utils#10]
Can ec2-net-utils-1.2-1.1.amzn2.src.rpm be removed from the repository and release files?

**Comment by nmeyerhans** [comment]
+1, that seems like it was included in the original GitHub import by mistake. 

cc @fred-lefebvre

**Comment by fred-lefebvre** [comment]
@mreiden : Thank you for catching this.  Fixed.
