### ISSUE TITLE
Only get 1 secondary private IP after assigned multiple secondary private ip to ENI

### ISSUE THREAD

**Issue by stevensu1977** [aws/amazon-ec2-net-utils#19]
I assigned multiple secondary private ip to my EC2 instance (Amazon Linux 2) and restart my network service (service network restart), but I only get 1 private ip with "ip addr" , 

I found get_secondary_ipv4s only return array first IP , ${ipv4s[@]:1} ,  I change to ${ipv4s[@]:2} or other number  if can be return other private ip ,  I think may be this is bug . 

get_secondary_ipv4s() {
  ipv4s=($(get_ipv4s))
  ec=$?
  echo "${ipv4s[@]:1}"
  return $ec
}

**Comment by stevensu1977** [comment]
I found root cause , Tokyo region , AMI is old , 

Amazon Linux 2 AMI (HVM), SSD Volume Type - ami-0f037327d64de9e49 (64-bit x86) / ami-0800db40f6e26830c (64-bit Arm)

for alias in ${aliases}; do
    if [[ ${secondaries[${alias}]} ]]; then
      unset secondaries[${alias}]


need change to  new version : 

for alias in ${aliases[@]}


It's work for me

**Comment by kai-alpha** [comment]
Hi my friend, the same fix was merged as #18 just 4 days ago but it isn't available via `amzn2-core` Yum repository yet. Our company lost $$$ from this bug 😠😠😠

**Comment by nmeyerhans** [comment]
Resolved with #18
