### ISSUE TITLE
Add ShellCheck to CI

### ISSUE THREAD

**Issue by kai-alpha** [aws/amazon-ec2-net-utils#20]
https://github.com/aws/amazon-ec2-net-utils/commit/89ff60855946ef330e9d5d8b3443bdcca43668be#diff-3aa0e32e6448cbc26df6ab19057db2c2bed15a6ca163a658eb601c0d656ec18eR299
This commit changed a flat whitespace-delimited string to a Bash array, which was (is) a serious bug until #18 updated the code which receives and interprets the array (by the present tense, I meant I'm still waiting for 1.5.1 to be available via `amzn2-core` Yum). Bugs like this would have easily been caught with popular static analysis tool like https://www.shellcheck.net/ (see also https://news.ycombinator.com/item?id=22212338 )

ShellCheck raises tons of warnings for this repository in its current shape (my VS Code automatically displays them with red squigglies), but I believe tools like `reviewdog` can limit its scope to a changed potion of the code under a CI environment so that you guys can gradually improve the code quality without being overwhelmed by a pile of warnings
* https://github.com/reviewdog/reviewdog#filter-mode

**Comment by nmeyerhans** [comment]
Done with #22
