### ISSUE TITLE
Support of CentOS7 

### ISSUE THREAD

**Issue by gauravmittal80** [aws/amazon-ec2-net-utils#32]
Hi,

Currently we do not see the support available for CentOS 7 AMI. Can we get the steps to build the RPM and install it manually in the AMI, so that when we create the EC2 instance the interfaces are configured properly.

Regards,
Gaurav

**Comment by nmeyerhans** [comment]
Hi @gauravmittal80. We don't directly develop or test on CentOS 7, but an RPM built from the 1.x branch of this repository should work there. The following steps will build the package for you:

  1.  `yum -y install git make systemd systemd-units rpm-build`
  2.  `git clone --branch=1.x --single-branch --depth 1 https://github.com/aws/amazon-ec2-net-utils.git`
  3.  `cd amazon-ec2-net-utils/`
  4.  `curl -LO 'https://github.com/aws/amazon-ec2-net-utils/archive/1.5.tar.gz'`
  5.  `rpmbuild --define "_sourcedir $PWD" -bb amazon-ec2-net-utils.spec`
  6.  `ls ~/rpmbuild/RPMS/noarch/`

If you run in to any issues or need to modify anything, feel free to open addition issues or pull requests as appropriate.

**Comment by gauravmittal80** [comment]
Thanks a lot @nmeyerhans. You are great... I really appreciate the help you provided. It worked for us. Thanks. I was thinking if these steps can be added in the ReadMe, it will help lots of people who may be in search of ec2-utils and find it missing.

Thanks again for helping.

**Comment by gauravmittal80** [comment]
Hi,

As we were testing the same cloud-init binary, we see that IPv6 address that gets assigned to the AWS EC2 instance is not reflecting inside the OS. To make it visible we had to add below 2 entries in the ifcfg-eth0.

echo "DHCPV6C=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth0
echo "IPV6INIT=yes" >> /etc/sysconfig/network-scripts/ifcfg-eth0
systemctl restart network 

After that I see the IP is visible in eth0, but since the proper routes are not added its not pingable on the network.

So you see this as a bug in cloud-init. I do not see this issue in Oracle Enterprise Linux 7.X.

Current version of cloud-init is 19.4.
